### ISSUE TITLE
Staking Documentation Requirements Unclear & 'fiat_in_no_fee' has zero value

### ISSUE THREAD

**Issue by rockmasterflex69** [eprbell/rp2#1]
I have (truncated) data (in my IN) that looks like this:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/rockm/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/rockm/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0000EE" vlink="#954F72">

Transaction   Type | Asset | Crypto In | Spot Price | USD In (No Fee) | USD In (With Fee) | USD Fee
-- | -- | -- | -- | -- | -- | --
Buy | XTZ | 3.443759 | 5.37 | 18.51 | 20 | 1.49
Buy | XTZ | 61.7067 | 3.19 | 197.01 | 200 | 2.99
Buy | XTZ | 18.45087 | 2.6 | 48.01 | 50 | 1.99
Staking | XTZ | 0.001164 | 3.53 | 0 | 0 | 0
Staking | XTZ | 0.001157 | 3.45 | 0 | 0 | 0
Staking | XTZ | 0.001049 | 3.09 | 0 | 0 | 0
Staking | XTZ | 0.001047 | 3.33 | 0 | 0 | 0
Staking | XTZ | 0.00119 | 3.29 | 0 | 0 | 0

</body>

</html>

Which appears to be causing the error:
rp2.rp2_error.RP2ValueError: Parameter 'fiat_in_no_fee' has zero value

The config is aligned, but it doesn't like my staking rows - what is supposed to be here?

**Comment by rockmasterflex69** [comment]
It looks like its a rounding error based on the output of coinbase, so it SHOULD be nonzero, but coinbase reports it as a zero.

HOWEVER, this sounds like it would be a good candidate for the tool making the calculation over the excel sheet enterer -> if i tell you its staking, the only thing the algorithm needs to calculate USD in is the spot price and the crypto in....

**Comment by eprbell** [comment]
It's an interesting observation: it may apply to all earn-like types (wages, interest, etc.). However, generally speaking, I prefer to err on the side of strict checks, so that the user can be made aware of potential problems in exchange / wallet outputs (like the problem you mentioned with Coinbase). This way the user can actively decide what is the best course of action in their specific situation. This is my current thinking, but let me mull it over for a bit.
