### ISSUE TITLE
Short term vs. long term gains

### ISSUE THREAD

**Issue by gbtorrance** [eprbell/rp2#100]
A question if you don't mind:

Is there a way with the reports to determine, for a particular coin, how much of my **remaining** holdings are subject to short-term vs. long-term capital gains (i.e. held for less than or greater than a year)?

For example, say I want to prepare for the end of the tax year by doing tax loss harvesting. I would like to know how much of of the sales I'm planning to do will be short term vs. long term.

Thanks!

**Comment by gbtorrance** [comment]
I guess, ideally, it would be a list of what remains of each purchase/IN, listed by date. (Of course what is short vs. long changes over time.)

**Comment by macanudo527** [comment]
Did you try the [open positions report](https://github.com/eprbell/rp2/blob/main/src/rp2/plugin/report/open_positions.py). I haven't used it a lot myself, but I think it comes close to what you are looking for. You might be able to modify it to suit your needs.

**Comment by gbtorrance** [comment]
Thanks @macanudo527. The "Asset" tab of the open positions report is the closest I've seen to what I'm looking for, but there is no break-down by dates, so it doesn't help with the ST vs. LT thing, unfortunately.

**Comment by gbtorrance** [comment]
@macanudo527 I will go ahead and close the issue. Thanks again.
