### ISSUE TITLE
Adding HIFO

### ISSUE THREAD

**Issue by YagiOoda** [eprbell/rp2#11]
I was wondering the possibility of adding HIFO to the existing FIFO and LIFO cost basis structures ([https://www.investopedia.com/terms/h/hifo.asp](https://www.investopedia.com/terms/h/hifo.asp)). It is available to use in the USA and would potentially help save a lot on taxes such that you're always selling the highest priced lot.

Unfortunately, my knowledge of python is more in the scripting/engineering realm, so I'm not sure how much help I would be on the coding aspect...

Thanks!

**Comment by eprbell** [comment]
I agree, HIFO would be good to have (and even more accounting methods). I don't have cycles right now to implement new accounting methods, but I'll happily review PRs. I'm labeling this issue "Help Wanted" to increase its visibility. 

RP2 has a robust plugin architecture that is designed for extending its functionality. Accounting methods are plugins: as such they are encapsulated and must implement a minimal, well-defined API. 

Here are a few pointers for anybody who would like to start working on this:
* [contribution guidelines](https://github.com/eprbell/rp2/blob/main/CONTRIBUTING.md#contributing-to-the-repository);
* [developer documentation](https://github.com/eprbell/rp2/blob/main/README.dev.md);
* [how to add a new accounting method plugin](https://github.com/eprbell/rp2/blob/main/README.dev.md#adding-a-new-accounting-method);
* the [LIFO](https://github.com/eprbell/rp2/blob/main/src/rp2/plugin/accounting_method/lifo.py) accounting method plugin is a good boilerplate for HIFO. I expect HIFO would have a similar internal structure to LIFO;
* remember that the plugin must be privacy-focused, just like RP2: it mustn't send user data anywhere.

**Comment by tonykau1** [comment]
Agreed, this would be valuable.  A few more considerations on the topic for whoever build on this:

To further minimize the tax, a combination of FIFO and HIFO may be necessary, accounting for long term cap gains rate vs short term (and short term would need to be an input of the user's expected incremental rate/bracket).  

LIFO may also be most efficient if all lots are short term and you want to let your oldest lost mature to LTCG as soon as possible.

**Comment by eprbell** [comment]
RP2's programmable plugin architecture makes all sorts of accounting methods possible: each one of them has to be implemented as a new plugin. It would be great to have many accounting method plugins, so that users can experiment and find what works best for their specific situation.

**Comment by ninideol** [comment]
Hello, I'm new to open source and I would like to try to add HIFO if it's still available

**Comment by eprbell** [comment]
That's great! I'll assign this to you. Let me know if you have any questions or comments.

**Comment by ninideol** [comment]
Thanks! It said in the contributing guidelines : "one feature per commit". Do I have to push only one commit on my pull request ?

**Comment by eprbell** [comment]
No: it just means to avoid more than one feature in one commit, but one feature (in this case the HIFO plugin) can be spread in multiple commits.

**Comment by ninideol** [comment]
Hi, to test the code, can i write a test file only for hifo method ? And how can i use hifo as accounting method in a terminal ? (it asks me to use choose only from fifo or lifo and i don't find where i can change it ?

**Comment by eprbell** [comment]
> Hi, to test the code, can i write a test file only for hifo method ? And how can i use hifo as accounting method in a terminal ? (it asks me to use choose only from fifo or lifo and i don't find where i can change it ?

Yes, absolutely: write an ODS file to test hifo-only.

As for the question on hifo not being listed by RP2 among the possible choices, here are a few hints:
* did you write your hifo plugin at `src/rp2/plugin/accounting_method/hifo.py`?
* does hifo.py contain a class called `AccountingMethod`?
* does the `AccountingMethod` class derive from `AbstractSpecificId`?

You probably already did this, but just in case: be sure to read the [links indicated in my comment above](https://github.com/eprbell/rp2/issues/11#issuecomment-1063562513) and use [lifo.py](https://github.com/eprbell/rp2/blob/main/src/rp2/plugin/accounting_method/lifo.py) as boilerplate, since hifo is going to be relatively similar to it. If you show me the code I can give you more precise feedback.

Hope this helps!

**Comment by ninideol** [comment]
Thank you for your response and your time ! I think i did all three hints it keeps ask me for lifo or fifo. I'm looking for what I missed.
And I'm struggling a bit on the `get_acquired_lot_for_taxable_event` method, in lifo it iterates by year but it can't be like that with price and it seems too much to find the highest one every time. Do have I to sort data so I can find highest easily ?

**Comment by eprbell** [comment]
To understand why it's happening, you can instrument the code in the following places:
* [_find_accounting_methods()](https://github.com/eprbell/rp2/blob/d7f9761f8f919c55dfa0bb31a0acbd7f42cdd0e1/src/rp2/rp2_main.py#L175)
* the [accounting method instantiation](https://github.com/eprbell/rp2/blob/d7f9761f8f919c55dfa0bb31a0acbd7f42cdd0e1/src/rp2/rp2_main.py#L67) snippet

A few prints there can probably shed some light.

Regarding your question on `get_acquired_lot_for_taxable_event()`, accounting_method plugins receive iterators to the acquired_lots and to the taxable_events in the `initialize()` method. This method can iterate over the lots and organize them in custom data structures that will allow the other methods easy access to the lots. The nature of these custom data structures depends on the semantics of the accounting methods. For LIFO I organized acquired lots in [a list and an AVL tree](https://github.com/eprbell/rp2/blob/d7f9761f8f919c55dfa0bb31a0acbd7f42cdd0e1/src/rp2/plugin/accounting_method/lifo.py#L59) per year. HIFO would be somewhat similar to LIFO but the sorting would be different for sure: in LIFO the AVL tree is sorted by timestamp, whereas in HIFO (if you use AVL trees) it would be sorted by amount (e.g. reimplement the `_get_avl_node_key()` method). I'm sure there are some other semantic differences between the two plugins, but I hope this gives you a few pointers.

**Comment by ninideol** [comment]
Thank you for the tips, I finally succeed to launch rp2 with hifo.

**Comment by ninideol** [comment]
Hi, sorry for the delay. I may have an implementation for HIFO accounting method, here it is : https://github.com/ninideol/rp2/tree/develop . Do you prefer a draft pull request maybe ?

**Comment by eprbell** [comment]
That's great! Thanks for working on this. Yeah, a PR would be best.

**Comment by ninideol** [comment]
Thanks ! I opened a PR

**Comment by eprbell** [comment]
Thanks, will review in the next few days.

**Comment by eprbell** [comment]
HIFO has been added in the latest version of RP2 (see #41).
