### ISSUE TITLE
Add support for Lowest-Cost In, First Out (ie. Highest-Tax First-Out, HTFO) for a specific Financial Year

### ISSUE THREAD

**Issue by quocodilian** [eprbell/rp2#118]
It would be great if crypto tax software could do the following:
Add support for Lowest-Cost In, First Out (ie. Highest-Tax First-Out, HTFO) for a specific Financial Year.

Rationale:
You might not have worked much in a particular Financial Year ("FY") (that's what we call it here in Australia), and so your taxable income for that FY may be unusually low.

You might prefer to specify that the crypto tax software matches "sell" transactions to lowest-cost "buy" transactions first, to maximise your capital gains / taxes from your crypto (and other investment-) transactions for that FY.

So for that FY, you pay more tax on your crypto (& other) investments than you could.

But you save the highest-cost "buy" transactions for future financial years where you worked much more and you are in a much higher tax bracket. So the overall effect should be: You pay much less tax by using this HTFO accounting method in those years where you worked much less.

This is especially true if you are several years behind in your tax compliance and need to catch up.. and in some financial years you worked a lot and in 1 or 2 FYs, you worked very little.

Ps. I've checked Syla and Koinly crypto tax software; neither of them support HTFO. I don't think any of the crypto tax software does.
This is probably just a "very nice to have" option.
I may opt to just use Syla and pay for it.. I don't really have time to try to write a quick & dirty software to allow LTFO or HTFO accounting methods for specific financial years :(

Anyways, just my two cents.

Thanks!
Huey

**Comment by eprbell** [comment]
RP2 currently supports FIFO, LIFO and HIFO, but more accounting method plugins can always be added as people see fit. Feel free to take a look at the technical documentation for [plugin programming](https://github.com/eprbell/rp2/blob/main/README.dev.md#adding-a-new-accounting-method).

**Comment by eprbell** [comment]
After refactoring the accounting method architecture, I added support for this: it's called LOFO (lowest in, first out). See [documentation](https://github.com/eprbell/rp2/blob/main/docs/supported_countries.md) and [implementation](https://github.com/eprbell/rp2/blob/main/src/rp2/plugin/accounting_method/lofo.py).
