### ISSUE TITLE
Language Independent Executable

### ISSUE THREAD

**Issue by rapus95** [eprbell/rp2#124]
Why isn't there a generic executable without a language code?
I live in Germany and need FIFO, which seems to be a provided approach for the general report. So why can't I just run?
```
rp2 -m FIFO -g en config.ini
```

**Comment by eprbell** [comment]
Because the country affects the output: currency symbol, are there long term cap gains, which accounting methods are supported, etc.

**Comment by rapus95** [comment]
But aren't these all just groups of settings which can also be passed via arguments? If there's no dali_de I might not get certain forms specific to my country, but the generic gathered output is still of much value, meaning those "reports valid for any country" (Full Report+Open positions).
Why can't we have an unspecialized label to execute to calrify that output will be unspecialized which simply requires currency/fiat symbol and method(FIFO/LIFO/etc) as cli arguments (and optionally the printing language)?
Because it feels totally weird to execute rp2_us etc for Germany when I only want the reports which aren't restricted to US.
What I'm asking for is a mode which produces only the output which is valid for all countries.

Or, worded differently, how can I get truly country-independent output? That means, using dali as gatherer and rp2 as the combining engine even though there's nothing specific for my country. Because the combined and sorted transaction list (which is country independent) helps a lot when handed to my tax consultant.

I hope that could clarify where I'm getting lost x)

**Comment by eprbell** [comment]
This discussion already happened a while back. My point back then was that I preferred having country parameters hard-coded into a country plugin to avoid user errors: I still prefer this option. However I'm coming around to seeing the usefulness of a "generic" country plugin that gets only three parameters (see https://github.com/eprbell/rp2/blob/main/README.dev.md#adding-support-for-a-new-country for details):
* country code;
* currency code; 
* long_term_capital_gain_period.

Such a plugin would immediately unlock a lot of countries for which we still don't have a country plugin.

**Comment by eprbell** [comment]
@rapus95, I added support for the generic country: see https://github.com/eprbell/rp2/blob/main/docs/supported_countries.md#generic. Can you try it out and let me know?

**Comment by rapus95** [comment]
I'll do as soon as I managed to import the data via dali
