### ISSUE TITLE
Adding liquidity pools

### ISSUE THREAD

**Issue by vichang** [eprbell/rp2#14]
Hey, great project. Was thinking of taking a stab at trying this out but I need to brush up. 

I had a question about liquidity pools (LPs). Has there any thought about how they would be handled? There's a few details here.

1. LPs are usually created with a 50/50 token split. However, they don't have to always be 50/50. There could be 2+ token assets that create a pool such as a 3 asset pool with an 80/20/20 split.
2. When you create an LP, you will know the value in. However, when you withdraw from an LP, pool rebalancing due to price fluctuations may have happened which means you wouldn't get the exact ratio of your tokens out.  IE: LP-IN (2 token-A & 4 token-B) -> LP-OUT (1 token-A & 3 token-B). 
3. You can partially withdraw from an LP
4. You can withdraw from the LP with just a single asset IE: LP-IN ($5 token-A & $6 token-b) -> LP-OUT ($11 token-A)
5. LPs still have a quantity attached to it as they are a token representation of your share of the pool.

I'm thinking of ways to handle this which could include

1. Consider an LP a token or separate "wallet" whose value is calculated based on USD value at time of deposit
2. On withdraw, deduct the LP quantity and calculate the USD withdraw value
3. Use the LP deposit USD value as the cost basis

It seems like it would work for tax purposes, but if a frontend were to ever be built, it could get tricky to display.

**Comment by eprbell** [comment]
Thanks for the question! Liquidity pool have been discussed before, see:
* [RP2 Issue 4](https://github.com/eprbell/rp2/issues/4)
* (RP2 DeFi Wiki)[https://github.com/eprbell/rp2/wiki/DEFI-Brainstorming
* [Liquidity Pool FAQ](https://github.com/eprbell/rp2/blob/main/docs/user_faq.md#how-to-handle-defi-yield-from-liquidity-pools): I just updated this one to explicitly mention liquidity pools (before it was just referring to locked-up crypto, which was less clear). 

I hope this helps!

**Comment by eprbell** [comment]
Hopefully the pointers above answered the question. Closing (feel free open a new issue if you have more feedback).
