### ISSUE TITLE
Documentation: input_files.md crypto_out_no_fee crypto_out_with_fee

### ISSUE THREAD

**Issue by stevendavis** [eprbell/rp2#15]
input_files.md 
OUT section
The description for both of these data elements says "excluding fees".  If I'm understanding it properly, crypto_out_with_fee is the total amount subtracted from the account including the fees.
```
crypto_out_no_fee: how much of the given cryptocurrency was sold or sent with the transaction (excluding fees).

crypto_out_with_fee (optional): how much of the given cryptocurrency was sold or sent with the transaction (excluding fees). If not provided, RP2 will compute this value automatically.
```

**Comment by eprbell** [comment]
Ouch... nice catch! Thanks for reporting it. I just fixed it.
