### ISSUE TITLE
Project cookiecutter template?

### ISSUE THREAD

**Issue by stevendavis** [eprbell/rp2#17]
Was rp2 created from a cookiecutter template? If so, may I ask, where could I find the template?

**Comment by eprbell** [comment]
No, it was written from scratch. I am now using it as a template for new Python projects though (e.g. [DaLI]( [uses](https://github.com/eprbell/dali-rp2) uses RP2's structure).

**Comment by stevendavis** [comment]
Thanks. I'm trying to get up-to-speed on the latest python packaging best practices.

**Comment by eprbell** [comment]
Ok: RP2 should be fairly close to Python packaging state of the art (as of about 1 year ago, when I did the research). Python packaging is a moving target though... If you see anything that should be updated in RP2 or DaLI let me know.

**Comment by stevendavis** [comment]
In my projects, I've been using the audreyfeldroy pypackage cookiecutter, here: https://github.com/audreyfeldroy/cookiecutter-pypackage

You might consider forking her project and customizing it with your preferences. Your work has some differences in the directory structure and the pre-commit hooks, black, isort, mypy, etc.  I'm considering adding some of these tools to my own projects.

**Comment by eprbell** [comment]
Yes, looks like there are already plenty of cookie cutter projects: there may not be need for a new one. Thanks for the pointer to Audrey's project. RP2 and DaLI are [src-based](https://bskinn.github.io/My-How-Why-Pyproject-Src/) projects: based on a quick look at Cookiecutter PyPackage, it seems to me it doesn't generate src-based structures, so it would not be compatible with RP2 and DaLI, but correct me if I'm wrong. Regardless, I'll take a look at it to see if there are configuration ideas I can bring into RP2 and DaLI.

**Comment by stevendavis** [comment]
I was wondering why you had a src directory. Always something new to learn.  Cookiecutter is flexible enough for a wide variety of project layouts.  I stumbled upon the hypermodern-python cookiecutter template tonight -- not endorsing it since I have never used it, but it does have the src layout: https://github.com/cjolowicz/cookiecutter-hypermodern-python

**Comment by eprbell** [comment]
Interesting, thanks for sharing.

**Comment by eprbell** [comment]
Closing the issue.
