### ISSUE TITLE
Data element provenance 

### ISSUE THREAD

**Issue by stevendavis** [eprbell/rp2#19]
I'm manually entering transaction data from multiple sources.  It's not unusual for a single transaction to have data provided by multiple exchanges, quote lookup sources, or blockchain viewers. Sometimes after being away from the data for a few days, I look at the spreadsheet and find myself wondering what was the source of a particular data element.

I've added new columns in the spreadsheet for this purpose. For example:
Timestamp, Timestamp Source, Spot Price, Spot Price Source, retc.

Maybe there is a better way to track this information.  Any suggestions on a good way to keep track of the sources of the data elements?

**Comment by eprbell** [comment]
Custom columns (that RP2 skips) with whatever extra information you need are definitely OK. Also the `Notes` column can be used to provide additional context in English, if needed. Finally the unique_id can be used to provide unique identity for the transaction (e.g. hash or exchange-specific id), if you have this information.
