### ISSUE TITLE
Cannot Open <filename>_rp2_full_report.ods - its corrupt

### ISSUE THREAD

**Issue by rockmasterflex69** [eprbell/rp2#2]
Neither excel nor an ODS viewer can open this file. There were no errors in the generation log and the other file, <filename>_tax_report.ods, opens just fine

**Comment by eprbell** [comment]
Can you try with Libre Office (https://www.libreoffice.org/)? I don't have Excel.

**Comment by eprbell** [comment]
I tried both output files for my own taxes (tax_report_us.ods and rp2_full_report.ods) in Google's ODS viewer and both worked ok. They also work with Libre Office.

**Comment by eprbell** [comment]
I removed references to Excel from the documentation and only left references to LibreOffice, which always worked fine for me. The ODS file is generated using the pyexcel-ezodf library. Closing the issue for now: if you notice a file corruption with LibreOffice, please reopen the issue.

**Comment by h3rb** [comment]
I can verify the input ods file works in Apache OpenOffice

**Comment by eprbell** [comment]
Could you also check the output files? I verified them with LibreOffice, but verifying OpenOffice as well would be good too.

**Comment by h3rb** [comment]
![rp2_screenshot_openoffice_calc](https://user-images.githubusercontent.com/2787368/149583794-7143fbf7-bb41-468c-aa7c-49e0ae21718b.png)

OpenOffice Calc, Windows 10

**Comment by h3rb** [comment]
![Screenshot_13](https://user-images.githubusercontent.com/2787368/149584087-3c29a0ee-601e-42aa-b93e-34016796d0a2.png)

**Comment by h3rb** [comment]
![Screenshot_14](https://user-images.githubusercontent.com/2787368/149584241-29584c85-3abd-43b8-9f4b-dae02820138a.png)

Other file
