### ISSUE TITLE
Final Balance in fifo_rp2_full_report.ods

### ISSUE THREAD

**Issue by stevendavis** [eprbell/rp2#21]
The Final Balance in fifo_rp2_full_report.ods (Tax tab) does not match my expected balance -- it is slightly too high.
The difference is exactly the amount of the last "crypto_fee" in the OUT section of the input file.

My input file has 3 OUT transactions.  The results looks as if the crypto fee for the first two transactions is correctly subtracted from the final balance, but the fee for the 3rd transaction is not subtracted.

**Comment by eprbell** [comment]
Could you upload a file that reproduces the issue?

**Comment by stevendavis** [comment]
Well, upon further review, my manual calculations match rp2 exactly.  The trouble is rp2 does not match my wallet. The difference is only a few cents, but I haven't found the root cause.  When I look at the transaction history in the wallet and sum the in/out transactions, it also matches rp2.  The only place where a different balance is visible is in the wallet dashboard. I will close this issue.  Sorry for the noise.

**Comment by eprbell** [comment]
No worries. If the balances don't match usually it's because some transaction is missing or has incorrect data.
