### ISSUE TITLE
Processing ALGO transactions with Coinbase Pro REST API. ValueError: Unknown format code 'f' for object of type 'str'

### ISSUE THREAD

**Issue by cryptocactus77** [eprbell/rp2#22]
Hi, I successfully used DaLI in preparation for RP2. I'm getting this error when I run rp2.

rp2_us -m fifo -o output/ -p rp2_ output/test_crypto_data.config output/test_crypto_data.ods
INFO: Country: us
INFO: Accounting Method: fifo
INFO: Configuration file: output/test_crypto_data.config
INFO: Input file: output/test_crypto_data.ods
INFO: Processing ADA
INFO: Processing ALGO
ERROR: Fatal exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rp2/ods_parser.py", line 258, in _process_constructor_argument_pack
    argument_pack[numeric_parameter] = RP2Decimal(f"{value:.11f}") if value is not None else None
ValueError: Unknown format code 'f' for object of type 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rp2/rp2_main.py", line 93, in _rp2_main_internal
    input_data: InputData = parse_ods(configuration=configuration, asset=asset, input_file_handle=input_file_handle)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rp2/ods_parser.py", line 128, in parse_ods
    _create_and_process_transaction(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rp2/ods_parser.py", line 168, in _create_and_process_transaction
    transaction: AbstractTransaction = _create_transaction(configuration, current_table_type, internal_id, row_values)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rp2/ods_parser.py", line 284, in _create_transaction
    argument_pack = _process_constructor_argument_pack(configuration, argument_pack, internal_id, "IntraTransaction")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rp2/ods_parser.py", line 260, in _process_constructor_argument_pack
    raise RP2ValueError(f"Argument '{numeric_parameter}' has non-numeric value: {value}") from exc
rp2.rp2_error.RP2ValueError: Argument 'crypto_received' has non-numeric value: __unknown
INFO: Log file: ./log/rp2_2022_04_02_16_28_00_882266.log
INFO: Generated output directory: output/
INFO: Done

**Comment by eprbell** [comment]
Looks like you have some unresolved ALGO transactions in Dali. You can tell from this mesaage: rp2.rp2_error.RP2ValueError: Argument 'crypto_received' has non-numeric value: __unknown

You can also look for __unknown in the Algo sheet in the DaLI-generated output.

I recommend reading the manual plugin section of the Dali documentation: https://github.com/eprbell/dali-rp2/blob/main/docs/configuration_file.md#manual-section-csv. In particular the part after the description of all the fields.

Let me know if you have more questions.

**Comment by eprbell** [comment]
To clarify further, the case that applies here is described in the manual plugin documentation as "partial transactions": 
"Partial transactions occur when an intra transaction is sent from a wallet or exchange supported by DaLI and is received at a wallet or exchange that is not yet supported by DaLI or viceversa. This causes DaLI to generate an incomplete transaction."

The user must provide the missing half of partial transactions as described in the document. In particular, use the `unique_id` field (typically the hash) to let DaLI know how to match the partial transaction generated by Dali with the user-written one.

**Comment by eprbell** [comment]
Closing for now. If you have any more questions, please reopen or open a new issue.
