### ISSUE TITLE
RecursionError: maximum recursion depth exceeded in comparison for Decimal.quantize()

### ISSUE THREAD

**Issue by rndstr** [eprbell/rp2#30]
I'm getting an endless loop which seems to be triggered by [`Decimal.quantize()`](https://github.com/python/cpython/blob/89697f7374ea947ebe8e36131e2d3e21fff6fa1d/Lib/_pydecimal.py#L2588) calling `RP2Decimal.__ne__` which then calls `RP2Decimal.__eq__` which then calls `Decimal.quantize()` again.

I presume there is something wrong with my numbers, which I have yet to investigate.
```
...
  File "/home/rndstr/venv3/lib/python3.10/site-packages/rp2/rp2_decimal.py", line 40, in __eq__
    return (self - other).quantize(CRYPTO_DECIMAL_MASK).__eq__(ZERO)
  File "/usr/lib/python3.10/_pydecimal.py", line 2588, in quantize
    if ans != self:
  File "/home/rndstr/venv3/lib/python3.10/site-packages/rp2/rp2_decimal.py", line 43, in __ne__
    return not self.__eq__(other)
  File "/home/rndstr/venv3/lib/python3.10/site-packages/rp2/rp2_decimal.py", line 40, in __eq__
    return (self - other).quantize(CRYPTO_DECIMAL_MASK).__eq__(ZERO)
  File "/usr/lib/python3.10/_pydecimal.py", line 2588, in quantize
    if ans != self:
  File "/home/rndstr/venv3/lib/python3.10/site-packages/rp2/rp2_decimal.py", line 43, in __ne__
    return not self.__eq__(other)
  File "/home/rndstr/venv3/lib/python3.10/site-packages/rp2/rp2_decimal.py", line 40, in __eq__
    return (self - other).quantize(CRYPTO_DECIMAL_MASK).__eq__(ZERO)
  File "/home/rndstr/venv3/lib/python3.10/site-packages/rp2/rp2_decimal.py", line 69, in __sub__
    return RP2Decimal(Decimal.__sub__(self, other))
  File "/usr/lib/python3.10/_pydecimal.py", line 1257, in __sub__
    return self.__add__(other.copy_negate(), context=context)
  File "/home/rndstr/venv3/lib/python3.10/site-packages/rp2/rp2_decimal.py", line 64, in __add__
    return RP2Decimal(Decimal.__add__(self, other))
  File "/usr/lib/python3.10/_pydecimal.py", line 1202, in __add__
    ans = self._rescale(exp, context.rounding)
  File "/usr/lib/python3.10/_pydecimal.py", line 2625, in _rescale
    if not self:
  File "/usr/lib/python3.10/_pydecimal.py", line 815, in __bool__
    return self._is_special or self._int != '0'
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by eprbell** [comment]
This looks like another Python 3.10 decimal issue, similar to issue #25. I haven't tested RP2 on Python 3.10: it does look like it's not working yet on that version of the language. The (non ideal) workaround is to use Python 3.9. If you find a way to modify PR #28 so that RP2 works on all versions of Python, I'll accept it.

**Comment by eprbell** [comment]
Since issue #25 seems due to some problem with your specific Python installation (see my latest comments there), this behavior might have the same origin. You may want to try uninstalling Python and reinstalling it.

**Comment by rndstr** [comment]
Well it's an endless loop which you can confirm following the link in my original post. Does not look like Python version related at all. The `crypto_example.ods` sample works fine, it's just my own sample has some input that `rp2` cannot handle and instead of throwing an exception (see the link in my original post), it goes to your overwritten method where you call quantize() again.

Now, I don't know which cell has an invalid value so I recommend adding verbosity to be able to better debug invalid values.

**Comment by rndstr** [comment]
Running the tests locally I also get the recursion error so it looks like it might be setup related. I don't know much about Python development and I have no clue how there can possibly be different behaviors in that regard, it's a clean Python install (through the package manager) and I reinstalled multiple times with different versions.

**Comment by rndstr** [comment]
If anyone cares, here is a CSV that fails:

```
IN,1,2,3,4,5,6,7,8,9,10,11,12
timestamp,exchange,holder,type,asset,crypto_in,spot_price,[crypto_fee],[fiat_fee],[fiat_in_fee],[fiat_in_nofee],[id],[notes]
2020-02-01T11:18Z,Kraken,self,BUY,ETH,107,1,0,,,,,x
TABLE END,,,,,,,,,,,,
,,,,,,,,,,,,
OUT,1,2,3,4,5,6,7,8,9,10,11,12
timestamp,exchange,holder,type,asset,crypto_out_nofee,spot_price,[crypto_fee],[fiat_fee],[crypto_out_fee],[fiat_out_nofee],[id],[notes]
2020-02-02T11:18Z,Kraken,self,SELL,ETH,50,1,0.00,0,,,,
TABLE END,,,,,,,,,,,,
```

and here one that succeeds
```
IN,1,2,3,4,5,6,7,8,9,10,11,12
timestamp,exchange,holder,type,asset,crypto_in,spot_price,[crypto_fee],[fiat_fee],[fiat_in_fee],[fiat_in_nofee],[id],[notes]
2020-02-01T11:18Z,Kraken,self,BUY,ETH,100,1,0,,,,,x
TABLE END,,,,,,,,,,,,
,,,,,,,,,,,,
OUT,1,2,3,4,5,6,7,8,9,10,11,12
timestamp,exchange,holder,type,asset,crypto_out_nofee,spot_price,[crypto_fee],[fiat_fee],[crypto_out_fee],[fiat_out_nofee],[id],[notes]
2020-02-02T11:18Z,Kraken,self,SELL,ETH,50,1,0.00,0,,,,
TABLE END,,,,,,,,,,,,
```

the only difference is for `crypto_in` to be `100` instead of `107` [rounding exception]

**Comment by eprbell** [comment]
Can you add  a print statement at /home/rndstr/venv3/lib/python3.10/site-packages/rp2/rp2_decimal.py", line 64, in __add__? Something like: 
```
print(self, other)
``` 
The last printed values before the exception should be the ones causing the problem in the add.

**Comment by rndstr** [comment]
it prints this
`-3.17757009345794393E-14 0E-13`

**Comment by eprbell** [comment]
> 

You have a small repro: that's good. Can you upload the ODS file instead of CSV and its related config? That way I can feed it directly to RP2 on my machine.

**Comment by rndstr** [comment]
uploaded it at https://github.com/rndstr/rp2/commit/3a973c8dc8c15958a908a37fa5542ee5dfc429bd

i wonder whether the Python decimal library is using something in my system that messes the rounding or accuracy up

**Comment by eprbell** [comment]
I tried your files and they worked on my machine:
```
> rp2_us loop.config loop.ods
 
INFO: Country: us
INFO: Accounting Method: fifo
INFO: Configuration file: loop.config
INFO: Input file: loop.ods
INFO: Processing ETH
INFO: Generating output for plugin 'rp2.plugin.report.rp2_full_report'
INFO: Plugin 'rp2.plugin.report.rp2_full_report' output: /private/tmp/output/fifo_rp2_full_report.ods
INFO: Generating output for plugin 'rp2.plugin.report.us.tax_report_us'
INFO: Plugin 'rp2.plugin.report.us.tax_report_us' output: /private/tmp/output/fifo_tax_report_us.ods
INFO: Log file: ./log/rp2_2022_04_12_21_22_19_512993.log
INFO: Generated output directory: output/
INFO: Done
```
I wonder if other Python packages using Decimal and high-precision math work on your machine: it might be an experiment worth trying.

**Comment by rndstr** [comment]
I ended up running it with Docker where it works, posting as it may help others running into the same issue:

Create `Dockerfile`
```
FROM python:3.9
WORKDIR /app
RUN pip3 install rp2
```

In same dir run
```bash
docker build --tag rp2 
```

Go to your file with `input.ods` and `input.config` files, run
```bash
docker run -it --rm --name rp2-script -v "$PWD":/usr/src/app -w /usr/src/app rp2 rp2_us input.config input.ods
```
