### ISSUE TITLE
JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig)

### ISSUE THREAD

**Issue by whatamidoingwrong** [eprbell/rp2#33]
Hi. I'm not sure what's wrong with my JSON file, but I keep getting this error when trying to run the program. (I'm new to python stuff, so it's probably just me making a dumb error. I'm not even sure if this is the correct place to ask you about it.) 

INFO: Country: us
INFO: Accounting Method: fifo
ERROR: Fatal exception occurred:
Traceback (most recent call last):
  File "c:\dev\2021-taxes\venv\lib\site-packages\rp2\rp2_main.py", line 73, 
[2021_tax.txt](https://github.com/eprbell/rp2/files/8497516/2021_tax.txt)
in _rp2_main_internal
    configuration: Configuration = Configuration(
  File "c:\dev\2021-taxes\venv\lib\site-packages\rp2\configuration.py", line 98, in __init__
    json_configuration: Any = json.load(configuration_file)
  File "C:\Program Files\Python38\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\Python38\lib\json\__init__.py", line 337, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
INFO: Log file: ./log/rp2_2022_04_15_12_49_50_163788.log
INFO: Generated output directory: output
INFO: Done

My JSON file looks like this:

{
    "in_header": {
	"timestamp": 1,
        "exchange": 3,
        "transaction_type": 5,
        "crypto_in": 6,
        "asset": 7,
        "spot_price": 8,
        “crypto_fee”: 9,
        "fiat_fee": 10,
        "unique_id": 11,
        "notes": 12,
        "holder": 13
    },

    "out_header": {
        "timestamp": 1,
        "exchange": 3,
        "transaction_type": 5,
        "crypto_out_no_fee": 6,
        "asset": 7,
        "spot_price": 8,
        “crypto_fee”: 9,
        "fiat_fee": 10,
        "unique_id": 11,
        "notes": 12,
        "holder": 13
    },

    "intra_header": {
        "timestamp": 1,
        "from_exchange": 3,
        "to_exchange": 4,
        "crypto_sent": 5,
        "crypto_received": 6,
        "asset": 7,
        "spot_price": 8,
        "unique_id": 11,
        "notes": 12,
        "from_holder": 13,
        "to_holder": 14
    },

    "assets": [
        "ADA",
        "ALGO",
        "AVAX",
        "CRO",
        "stETH",
        "ETH",
        "SHIB",
        "xSHIB"
    ],
    "exchanges": [
        "Bank",
        "Binance.US",
        "Coinbase",
        "Coinbase Pro",
        "Trust Wallet (BSC Smart Chain)",
        "Trust Wallet (BNB BEP-2)",
        "Trust Wallet (ETH & ERC-20)",
        "Trust Wallet (ALGO)"
    ],
    "holders": [
        "Me"
    ]
}

What am I doing wrong?  Any help would be greatly appreciated. Thank you.

**Comment by eprbell** [comment]
You're using invalid quotes for `crypto_fee` both in the `in_header` and `out_header` sections: it should be `"` instead of `“`.

**Comment by whatamidoingwrong** [comment]
You're awesome. Thank you so much.

**Comment by eprbell** [comment]
:-)
