### ISSUE TITLE
Multiple account balance records in fifo_rp2_full_report.ods

### ISSUE THREAD

**Issue by stevendavis** [eprbell/rp2#40]
Not sure if this is a bug or a feature.  In the Tax-tab, I was expecting a single row containing the account balance at each exchange.  Instead, I see something like this (contents changed a bit to preserve privacy):

![image](https://user-images.githubusercontent.com/7604948/169723640-c18d4247-1436-4e34-a666-4cb8ecd8d800.png)

For some reason, I'm seeing two entries for the same token at exchangeBB. The actual balance of exchangeBB is the sum of the two entries.

**Comment by eprbell** [comment]
Hm... strange. Definitely not a feature. Can you check in your config file both the `assets` and the `exchanges` sections? Do they contain what you expect (i.e. no duplicate or strange values)?

**Comment by stevendavis** [comment]
Yes, you're right.  I had the exchange listed twice in the config file with different camel-case / lower-case spellings.  Thanks again for the quick reply.  Closing.
