### ISSUE TITLE
Document the release steps

### ISSUE THREAD

**Issue by stevendavis** [eprbell/rp2#42]
Hi @eprbell, may I ask, could you document the step-by-step process for releasing a new distribution? For now, this is something entirely under your control, but maybe some time in the future, other community members may need to do it.  I can see you are using bumpversion, there is a change log, tags in the repo, releases on GitHub, the distribution on PyPi, and maybe other artifacts I'm missing.  The exact sequence of producing the artifacts is unclear.

**Comment by eprbell** [comment]
Good idea, I'll document that.

**Comment by eprbell** [comment]
I added a section to README.dev.md, both in RP2 and in DaLI.

**Comment by stevendavis** [comment]
Thank you for adding the release creation steps.  It will be helpful as the community grows.

Something I noticed is the order of updating the changelog and bumping the version. In practice, it looks like you have been running bumpversion after updating the changelog.  That way, the tagged version correctly contains the change history.

I'm also wondering, would it make sense to have bumpversion automatically set the version number in the changelog while setting the version number everywhere else?  Not sure if it's possible or even desirable, but I'm envisioning a static string like "In Progress", that would be changed to the new version number.

**Comment by eprbell** [comment]
I like your attention to detail! You're right: technically bumpversion should be the last thing before push. I fixed that in the documents. 

As for updating CHANGELOG.md automatically, I thought about it and I experimented with it in the very early days, but the process seemed too error-prone (it was easy to forget to use the keyword), so I decided to use the manual approach.

**Comment by eprbell** [comment]
Closing this for now. Please reopen if you have more concerns.
