### ISSUE TITLE
Implement JPN country plugin

### ISSUE THREAD

**Issue by macanudo527** [eprbell/rp2#43]
I read through the country plugin documentation and it seems like the main thing to define is `long_term_capital_gain_period()`. However, Japan has no long term capital gains benefits. Everything crypto is taxed as short term. To be more specific, it is taxed as regular income. 

So, how should I define this?

**Comment by eprbell** [comment]
You can implement it as:
```
return sys.maxsize
```
The value is so large that every taxable event will be short term.

**Comment by eprbell** [comment]
This is now merged.
