### ISSUE TITLE
Investment Expenses Tab

### ISSUE THREAD

**Issue by whatamidoingwrong** [eprbell/rp2#45]
Hello,

I just have a quick question for you.

In the tax-friendly output file: Are the transactions in the "Investment Expenses" tab _already_ factored into the "Capital Gains" tab? 
Do "Investment Expenses" get their own tab simply for easy record-keeping, or, do I need to manually go through my "Capital Gains" transactions and adjust the cost basis myself, based upon what I see in the "Investment Expenses" tab?

Thank you!

**Comment by eprbell** [comment]
The transactions in the "Capital Gains" tab are self-contained and there is no need to adjust their cost basis. The transactions in "Investment Expenses" tab are also self-contained: they affect the in-out lot relationship and so they are reported in the output (more on this in the [FAQ](https://github.com/eprbell/rp2/blob/main/docs/user_faq.md#if-i-transfer-cryptocurrency-between-two-accounts-i-own-is-the-fee-taxable)). Hope this helps.

**Comment by whatamidoingwrong** [comment]
Got it.  Thank you.
