### ISSUE TITLE
Margin trading

### ISSUE THREAD

**Issue by jtourt** [eprbell/rp2#46]
Does RP2 handle margin trading?   Leveraged trades.   Shorting.  Selling borrowed assets that are bought later to repay the loan.

**Comment by eprbell** [comment]
While I don't have direct experience with margin trading, my understanding is that such taxable events generate normal capital gains and losses (see this article for more on the topic: https://coinledger.io/blog/crypto-margin-trades-taxes). So RP2 should support these transaction types normally.

**Comment by eprbell** [comment]
Closing the issue: if you have more questions feel free to open a new issue.
