### ISSUE TITLE
Where to put buying crypto with cash or using swapping site?

### ISSUE THREAD

**Issue by swissarmybox** [eprbell/rp2#5]
First of all, great project! This seems to be exactly what I need. I would like to contribute as well.

I have a few questions/suggestions:
1. How to account for buying crypto with cash from a random person on the street?
2. How to account for using swapping sites like simpleswap.io / changenow.io
3. Correct me if I am wrong, but where do we get crypto fee value? I think inside the exhange this can easily be done, but outside the exchange, where do we get the transaction fee value? Sorry this must be a stupid question
4. Where to get spot prices the best? I guess inside the exchange this can be done easily, but outside the exchange, we just have to rely on coinmarketcap.com?
5. What date-time is best representing a transaction? Is it the date time transaction is initiated or when the date time crypto is received/sent? Because an exchange might say the transaction run at a certain time, but then we see on the chain it is a different time?
6. I'm thinking maybe we could provide a column metadata that keeps track of transaction hash/addresses, maybe will be useful for audit?

Sorry for the long questions. Awesome project again!

**Comment by eprbell** [comment]
Thanks for the feedback, glad you like the project! Regarding your questions:
1. You could capture this scenario as follows: add a name like "rando_from_street" to the exchanges section in the config file, and then use "rando_from_street" as the exchange field of a IN/BUY transaction (basically treat "rando_from_street" as if it was an exchange). You can also use the Notes field to describe the transaction/context. See the [input files](https://github.com/eprbell/rp2/blob/main/docs/input_files.md) section of the documentation for more details on file formats.
2. I'm not familiar with these sites: do they just do plain coin swaps? If so check the [swap question in the FAQ](https://github.com/eprbell/rp2/blob/main/docs/user_faq.md#how-to-handle-conversion-of-a-cryptocurrency-to-another).
3. Exchanges typically provide fee values in statements/reports. Can you elaborate on what you mean by "outside the exchange"? 
4. Exchanges typically provide spot prices in statements/reports. However there are several websites that provide that info in case you don't have it: Coinmarketcap, [Yahoo](https://finance.yahoo.com/quote/BTC-USD/history/) and others.
5. I would use the timestamp that comes with the generated report from exchanges/wallets.
6. Interesting idea. Currently hashes and addresses can be captured in the Notes field, but perhaps they deserve their own column.

**Comment by swissarmybox** [comment]
> Thanks for the feedback, glad you like the project! Regarding your questions:
> 
>     1. You could capture this scenario as follows: add a name like "rando_from_street" to the exchanges section in the config file, and then use "rando_from_street" as the exchange field of a IN/BUY transaction (basically treat "rando_from_street" as if it was an exchange). You can also use the Notes field to describe the transaction/context. See the [input files](https://github.com/eprbell/rp2/blob/main/docs/input_files.md) section of the documentation for more details on file formats.
> 
Yeah this makes sense, thanks! 

>     2. I'm not familiar with these sites: do they just do plain coin swaps? If so check the [swap question in the FAQ](https://github.com/eprbell/rp2/blob/main/docs/user_faq.md#how-to-handle-conversion-of-a-cryptocurrency-to-another).
> 
Yes it is basically just plain coin swap. Okay yeah I think that makes senes!

>     3. Exchanges typically provide fee values in statements/reports. Can you elaborate on what you mean by "outside the exchange"?
> 
By outside the exchange I mean like people executing transactions. Here is one sample random transaction I found on etherscan

https://etherscan.io/tx/0x53293f7f78611f6e33630783b7145e64528d2b33bdb024771cb2156027d96ad0

Transaction Fee:
0.00330983293902828 Ether ($8.47)

Gas Price:
0.000000086781146802 Ether (86.781146802 Gwei)

Sorry I am quite newb in crypto in terms of taxation. In this case, the transaction fee should be the 0.033... Ether or the 0.000000086 Ether?

>     4. Exchanges typically provide spot prices in statements/reports. However there are several websites that provide that info in case you don't have it: Coinmarketcap, [Yahoo](https://finance.yahoo.com/quote/BTC-USD/history/) and others.
> 
Gotcha thanks. That makes sense.

>     5. I would use the timestamp that comes with the generated report from exchanges/wallets.
> 

Yeah this makes sense.

>     6. Interesting idea. Currently hashes and addresses can be captured in the Notes field, but perhaps they deserve their own column.

I was experimenting on using this library https://cytoscape.org/ for my crypto visualization project. I thought it could be an interesting idea if an audit comes in.

**Comment by eprbell** [comment]
> > 3. Exchanges typically provide fee values in statements/reports. Can you elaborate on what you mean by "outside the exchange"?
> 
> By outside the exchange I mean like people executing transactions. Here is one sample random transaction I found on etherscan
> https://etherscan.io/tx/0x53293f7f78611f6e33630783b7145e64528d2b33bdb024771cb2156027d96ad0
> Transaction Fee: 0.00330983293902828 Ether ($8.47)
> Gas Price: 0.000000086781146802 Ether (86.781146802 Gwei)
> Sorry I am quite newb in crypto in terms of taxation. In this case, the transaction fee should be the 0.033... Ether or the 0.000000086 Ether?

Got it, thanks for the clarification. You would only use the transaction fee in RP2: the gas price is just the cost per unit of gas (the higher it is, the higher the probability of the transaction being included in the next block).

> > 6. Interesting idea. Currently hashes and addresses can be captured in the Notes field, but perhaps they deserve their own column.
> I was experimenting on using this library https://cytoscape.org/ for my crypto visualization project. I thought it could be an interesting idea if an audit comes in.

Looks like an interesting library: I was thinking more in terms of a GUI alternative to the RP2 CLI interface (to extend the user base to non-shell users), but I'm curious to see what you come up with using this library.

Thanks for the questions and feedback!

**Comment by eprbell** [comment]
All the questions have been answered. I added the hash/address column in [feature requests wiki](https://github.com/eprbell/rp2/wiki/Feature-Requests), which is used to keep track of ideas from users. Closing the issue.

**Comment by eprbell** [comment]
I added a new column (and transaction constructor parameter) called unique_id to keep track of hash, as proposed in this issue (it's in RP2 v0.9.14): addresses are not necessary because they can be derived from hash. The unique_id can be used for hash with IntraTransaction and for exchange-specific unique_id in In/OutTransaction.
