### ISSUE TITLE
INstallation issue

### ISSUE THREAD

**Issue by dhldmoore** [eprbell/rp2#7]
Just tried installing rp2 but I get the following errors on the powershell page:
PS C:\WINDOWS\system32> pip install rp2
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000191A1813DF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))': /simple/rp2/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000191A1813BB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))': /simple/rp2/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000191A1840400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))': /simple/rp2/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000191A1840580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))': /simple/rp2/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000191A1840700>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))': /simple/rp2/
ERROR: Could not find a version that satisfies the requirement rp2 (from versions: none)
ERROR: No matching distribution found for rp2

THought maybe there was a networking issue due to me trying to install it on my work laptop and being on a work network. I detached the network cable and got on a normal network off of the work network and got the same errors.  Any ideas?

**Comment by eprbell** [comment]
It does look like a connection issue, not related to RP2: the server is actively refusing to connect with your machine. I think you may have the same problem doing pip install with other pypi packages. Is your work machine using a proxy/VPN, or is it running some monitoring software? You can try:
* speaking with your IT department and telling them pup install doesn't work on your machine or
* use a non-work machine.

**Comment by dhldmoore** [comment]
That is why I disconnected from my work network and got on another network that has direct access to the internet. Let me try it one more time to ensure I have a good connection out side of my work network. I'll respond later.

**Comment by eprbell** [comment]
If you have a proxy / VPN or monitoring software that interferes with connectivity, switching network won't help. Try pip installing some other package.

**Comment by eprbell** [comment]
Closing this issue since it doesn't seem to be related to RP2.
