### ISSUE TITLE
Question about "Open Positions by Asset" report

### ISSUE THREAD

**Issue by gbtorrance** [eprbell/rp2#81]
Regarding the "Open Positions by Asset" report:

I believe I understand what "USD Per Unit Cost Basis" means. (It's self-explanatory.) But I don't understand "USD Unrealized Cost Basis" and "Cost Basis Weight %". Can you please provide some explanation for these?

Thanks a lot!

**Comment by eprbell** [comment]
There is a legend tab with explanation of each field. However in case the explanation needs to be improved, @mdavid217 could you take this question? Thanks!

**Comment by gbtorrance** [comment]
Oh, I had forgotten about the Legend. After reviewing the descriptions it makes sense now. Thank you! (Closing the ticket.)
