### ISSUE TITLE
RP2 process runs after "DONE"

### ISSUE THREAD

**Issue by gbtorrance** [eprbell/rp2#85]
When I run `rp2_us`, even after the reports are generated and the logs say `INFO: Done` the process continues to run for a very long time with actual CPU utilization (0.3% - 1.7% typically). Eventually it stops on its own. (I don't know exactly how long it runs after `INFO: Done`, as I left the computer, but it was at least 10 minutes.)

Is it still doing actual "work" during this period, or is there something wrong? Thanks.

**Comment by eprbell** [comment]
After logging "Done", RP2 exits and does nothing else. Can you paste info on how you observed the behavior (i.e. `ps aux` or similar)?

**Comment by gbtorrance** [comment]
OK, weird. So here is an execution of rp2 in the background terminal. Notice how the prompt has not yet returned. It shows `INFO: Done`, but is seemingly still running. I then did a `ps` in the foreground terminal, and it shows it is still running. It has been like this for 5+ minutes now.

![image](https://user-images.githubusercontent.com/16735709/210070240-eb43f431-cc2b-450e-a943-de7613d95b6f.png)

For what it's worth, this is running in a VirtualBox guest (Linux Mint 21). It doesn't have a lot of resources and is kind of slow (though it got to `INFO: Done` fairly quickly). It has access to 1 CPU, and is using swap space for virtual memory as actual memory is limited. (I'm using a VM rather than running on the host because the version of Linux Mint I'm running on the host has both python 2 and python 3, and I was running into issues with getting rp2 to run properly.)

**Comment by gbtorrance** [comment]
I anticipated you might ask, so I freed up resources on the host and allocated much more to the guest. 4 CPUs and 4 GB of total RAM. This time it executed fine and ended promptly. So it seems it was purely a resources issue and not related to rp2. Sorry for the hassle. Please feel free to close the ticket. Thanks.

**Comment by gbtorrance** [comment]
After some further tests I settled on 2 CPUs and 2.5 GB RAM for the guest VM. That seems to perform quite well (and exits promptly). I could probably even reduce more, but that seems fine for now.

**Comment by eprbell** [comment]
Sounds good: it does sound like an issue with low resource systems.
